name: Bank Backend Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 381492269344.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPO: bank-backendapi

jobs:
  Continues-Integration_build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: dizzydesire/Bank-Backend.git
        ref: main

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build Docker image
      run: docker build -t bank-app-backend:latest .

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} \
        | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

    - name: Tag Docker image
      run: |
        docker tag bank-app-backend:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ github.run_number }}

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ github.run_number }}

    - name: Clean up Docker images locally
      run: |
        docker rmi bank-app-backend:latest || true
        docker rmi ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ github.run_number }} || true

    - name: Clean up workspace
      run: rm -rf ./*

  Continues-Update_k8s_manifest:
    runs-on: ubuntu-latest
    needs: Continues-Integration_build_and_push

    steps:
    - name: Clone Kubernetes manifest repo
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      run: |
        git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/dizzydesire/Kubernetes-manifest.git
        cd kubernetes-manifest
        git config --global user.email "desireoduma@outlook.com"
        git config --global user.name "dizzytech"

        # Update image tag in manifest
        sed -i "s|${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:.*|${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ github.run_number }}|g" ./bank-project/backendapi.yaml

        git add ./bank-project/backendapi.yaml
        git commit -m "Update backendapi image to version ${{ github.run_number }}"
        git push origin main
