name: Dependency-Check → DefectDojo

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  depcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build (resolve dependencies)
        run: mvn -q -DskipTests clean package

      - name: Run OWASP Dependency-Check (Maven plugin, XML report)
        run: |
          mvn -DskipTests org.owasp:dependency-check-maven:check \
            -Dformat=XML \
            -DoutputDirectory=target \
            -DnvdApiKey=${{ secrets.NVD_API_KEY }}

      - name: Show quick vuln count
        run: |
          echo "Vulnerability count:"
          grep -c "<vulnerability>" target/dependency-check-report.xml || true

      - name: Upload report artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-xml
          path: target/dependency-check-report.xml

      - name: Import to DefectDojo (use engagement ID)
        env:
          DD_URL: ${{ secrets.DD_URL }}            # e.g., http://13.222.254.180:8080
          DD_TOKEN: ${{ secrets.DD_TOKEN }}        # your Dojo API token
          DD_ENGAGEMENT_ID: ${{ secrets.DD_ENGAGEMENT_ID }}  # e.g., 1
        run: |
          curl -sfSL -X POST "${DD_URL}/api/v2/import-scan/" \
            -H "accept: application/json" \
            -H "Authorization: Token ${DD_TOKEN}" \
            -H "Content-Type: multipart/form-data" \
            -F "scan_type=Dependency Check Scan" \
            -F "file=@target/dependency-check-report.xml;type=application/xml" \
            -F "engagement=${DD_ENGAGEMENT_ID}" \
            -F "scan_date=$(date +%F)" \
            -F "active=true" \
            -F "verified=true"
